#!/bin/bash
# Builds "NICKII AI.app" on the Desktop: a double-clickable launcher that opens
# a Terminal window and runs scripts/nickii.sh.
#
#   ./scripts/make-launcher.sh
#
# It deliberately opens a visible Terminal rather than running silently. On a
# show day the useful question is not "did it launch" but "is whisper up, is
# the certificate valid, is the picture 1920 wide", and those answers have to
# be somewhere she can see them.
#
# Run this again after moving the repo: the launcher stores an absolute path.

set -euo pipefail

cd "$(dirname "$0")/.."
REPO="$PWD"
APP="${1:-$HOME/Desktop/NICKII AI.app}"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key>            <string>NICKII AI</string>
  <key>CFBundleDisplayName</key>     <string>NICKII AI</string>
  <key>CFBundleIdentifier</key>      <string>com.nickii.launcher</string>
  <key>CFBundleVersion</key>         <string>2.0</string>
  <key>CFBundleShortVersionString</key><string>2.0</string>
  <key>CFBundlePackageType</key>     <string>APPL</string>
  <key>CFBundleExecutable</key>      <string>launch</string>
  <key>CFBundleIconFile</key>        <string>nickii</string>
  <key>NSHighResolutionCapable</key> <true/>
</dict>
</plist>
PLIST

cat > "$APP/Contents/MacOS/launch" <<LAUNCH
#!/bin/bash
# Generated by scripts/make-launcher.sh. Rerun that if the repo moves.
open -a Terminal "$REPO/scripts/nickii.sh"
LAUNCH
chmod +x "$APP/Contents/MacOS/launch"

# ---------------------------------------------------------------- icon
# Built from the same orb the app uses, so the Desktop, the Dock and the iPad
# Home Screen all carry one mark.
if [ -f public/icons/icon-512.png ]; then
  SET="$(mktemp -d)/nickii.iconset"
  mkdir -p "$SET"
  for s in 16 32 128 256 512; do
    sips -z $s $s public/icons/icon-512.png --out "$SET/icon_${s}x${s}.png" >/dev/null 2>&1
    d=$((s * 2))
    sips -z $d $d public/icons/icon-512.png --out "$SET/icon_${s}x${s}@2x.png" >/dev/null 2>&1
  done
  iconutil -c icns "$SET" -o "$APP/Contents/Resources/nickii.icns" 2>/dev/null \
    && echo "icon built" || echo "icon build skipped"
  rm -rf "$(dirname "$SET")"
fi

# Make Finder notice the new bundle rather than showing a blank icon.
touch "$APP"
/usr/bin/touch -c "$APP" 2>/dev/null || true

echo
echo "Launcher created:"
echo "  $APP"
echo
echo "Double-click it to bring the system up. The first launch will ask"
echo "permission to open Terminal, which is macOS being careful, not an error."
echo
